import assert from 'node:assert/strict'
import test from 'node:test'
import { CosMatterPolicyClient } from '../lib/client.js'
import { apply, inject, name } from '../lib/index.js'
const catalogue = { catalogue_api_version: '2.0', plugins: [{ plugin_id: 'graph.plan_assist', required_authorizations: ['mission_scoped_egress_consent'], contract: {} }], trust_status: 'static_catalogue_not_plugin_execution_or_evidence_acceptance' }
const plan = { mission_id: 'mission_1', plugin_id: 'graph.plan_assist', permitted: false, reason: 'missing_explicit_authorization', missing_authorizations: ['deepseek_request_consent'], requires_human_review: true, next_boundary: 'No execution.', trust_status: 'nonexecuting_authorization_plan_not_consent_or_execution' }
test('client reads only a bounded non-sensitive catalogue', async () => { const client = new CosMatterPolicyClient({}, async () => new Response(JSON.stringify(catalogue), { status: 200 })); assert.equal((await client.catalogue()).plugins.length, 1) })
test('client rejects non-loopback settings and malformed policy plans', async () => { assert.throws(() => new CosMatterPolicyClient({ baseUrl: 'https://example.com' })); const client = new CosMatterPolicyClient({}, async () => new Response(JSON.stringify({ ...plan, trust_status: 'executed' }), { status: 200 })); await assert.rejects(() => client.authorizationPlan('run_1', 'graph.plan_assist', []), /invalid/) })
test('DSH apply registers catalogue and non-executing policy tools', async () => { const tools = []; const events = []; let dispose; const previous = globalThis.fetch; globalThis.fetch = async url => new Response(JSON.stringify(String(url).endsWith('/api/plugins') ? catalogue : plan), { status: 200 }); apply({ tools: { register: tool => tools.push(tool) }, emit: (event, payload) => events.push([event, payload]), effect: effect => { dispose = effect() } }); assert.equal(name, 'cosmatter-policy'); assert.deepEqual(inject, ['tools']); assert.deepEqual(tools.map(tool => tool.name), ['cosmatter_plugin_catalogue', 'cosmatter_plugin_authorization_plan']); assert.equal((await tools[0].execute({}, { signal: new AbortController().signal })).trust_status, catalogue.trust_status); assert.equal((await tools[1].execute({ run_id: 'run_1', plugin_id: 'graph.plan_assist', authorizations: [] }, { signal: new AbortController().signal })).trust_status, plan.trust_status); assert.equal(events.length, 2); dispose(); globalThis.fetch = previous })
