"""Competition-submission readiness checks without packaging private data."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .external_resources import ExternalResourceDisclosureError, load_external_resource_disclosure
from .evaluation_operational_disclosure import (
    EvaluationOperationalDisclosureError,
    load_api_cost_latency,
    load_failure_case_log,
)
from .evaluation_run_record import EvaluationRunRecordError, reviewed_evaluation_run_record
from .corpus_preparation import CorpusPreparationError, load_corpus_manifest
from .ui_export import UiExportError, _mission_from_payload


SUBMISSION_READINESS_SCHEMA_VERSION = "1.0"


class SubmissionReadinessError(ValueError):
    """Raised when a requested submission artifact cannot be inspected."""


def submission_readiness(*, repository_root: Path, run_dir: Path | None = None) -> dict[str, Any]:
    """Return explicit readiness checks; false means a human must resolve it.

    The check intentionally never opens ``.env`` files or scans private run
    content. It reads only named public repository files and safe report
    manifests generated by the report exporter.
    """
    required_files = {
        "source_package": repository_root / "pyproject.toml",
        "readme": repository_root / "README.md",
        "reproducibility_guide": repository_root / "REPRODUCIBILITY.md",
        "license": repository_root / "LICENSE",
        "contributing_guide": repository_root / "CONTRIBUTING.md",
        "citation_metadata": repository_root / "CITATION.cff",
        "reproducibility_config": repository_root / "configs" / "reproducibility.example.json",
        "python_dependency_lock": repository_root / "requirements.lock",
        "frontend_lockfile": repository_root / "frontend" / "package-lock.json",
        "gitignore": repository_root / ".gitignore",
    }
    checks = {name: path.is_file() and path.stat().st_size > 0 for name, path in required_files.items()}
    config = _load_json(required_files["reproducibility_config"]) if checks["reproducibility_config"] else None
    checks.update(_reproducibility_config_checks(config))
    checks["python_source_present"] = _has_files(repository_root / "src" / "cosmatter", ".py")
    checks["python_tests_present"] = _has_files(repository_root / "tests", ".py")
    checks["frontend_source_present"] = _has_files(repository_root / "frontend" / "src", (".ts", ".tsx", ".css"))
    ignored = required_files["gitignore"].read_text(encoding="utf-8") if checks["gitignore"] else ""
    checks["secrets_ignored"] = ".env" in ignored and "runs/" in ignored and ".private/" in ignored
    report_checks: dict[str, bool] = {}
    if run_dir is not None:
        package = run_dir / "latex_submission"
        names = {"main.tex", "references.bib", "citation_audit.json", "latex_report_manifest.json", "main.pdf"}
        report_checks = {f"latex_{name}": (package / name).is_file() and (package / name).stat().st_size > 0 for name in names}
        audit = _load_json(package / "citation_audit.json") if report_checks["latex_citation_audit.json"] else None
        manifest = _load_json(package / "latex_report_manifest.json") if report_checks["latex_latex_report_manifest.json"] else None
        report_checks["latex_citation_bijection"] = isinstance(audit, dict) and audit.get("citation_bibliography_bijection") is True
        report_checks["latex_evidence_source_disclosure"] = isinstance(manifest, dict) and manifest.get("accepted_evidence_source_disclosure_coverage") == 1.0
        disclosure_path = run_dir / "external_resource_disclosure.json"
        try:
            load_external_resource_disclosure(disclosure_path)
            report_checks["run_external_resource_disclosure"] = True
        except ExternalResourceDisclosureError:
            report_checks["run_external_resource_disclosure"] = False
        evaluation_record_path = run_dir / "real_corpus_evaluation_run_record.json"
        if evaluation_record_path.is_file():
            try:
                mission_payload = _load_json(run_dir / "mission.json")
                mission = _mission_from_payload(mission_payload)
                corpus = load_corpus_manifest(run_dir / "corpus_manifest.json", mission.mission_id)
                if corpus is None:
                    raise CorpusPreparationError("missing corpus manifest")
                reviewed_evaluation_run_record(
                    run_dir=run_dir, manifest=corpus, mission_id=mission.mission_id,
                    payload=_load_json(evaluation_record_path),
                )
                report_checks["run_real_evaluation_record_consistent"] = True
            except (SubmissionReadinessError, EvaluationRunRecordError, EvaluationOperationalDisclosureError, CorpusPreparationError, UiExportError, ValueError):
                report_checks["run_real_evaluation_record_consistent"] = False
        checks.update(report_checks)
    required = tuple(checks)
    return {
        "schema_version": SUBMISSION_READINESS_SCHEMA_VERSION,
        "trust_status": "submission_readiness_file_check_not_scientific_or_reference_authenticity_assessment",
        "run_scoped": run_dir is not None,
        "checks": checks,
        "ready": all(checks[name] for name in required),
        "required_human_checks": [
            "Verify every cited bibliographic record and source locator against the authorized original source.",
            "Confirm actual external resource versions, access dates, licenses, costs, and permitted data redistribution.",
            "Confirm all performance claims are supported by a real frozen evaluation record, not synthetic fixtures.",
            "Confirm the chosen public repository release and all visual assets are cleared for the stated MIT release boundary.",
        ],
    }


def _load_json(path: Path) -> object:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise SubmissionReadinessError(f"submission readiness JSON is invalid: {path.name}") from error


def _reproducibility_config_checks(config: object) -> dict[str, bool]:
    """Check the public source-level contract required for preliminary review.

    It intentionally validates declared defaults only.  A real run must still
    record its actual parameters and resource disclosure separately.
    """
    if not isinstance(config, dict):
        return {
            "seed_declared": False,
            "key_parameters_declared": False,
            "resources_disclosed": False,
            "runtime_versions_declared": False,
        }
    seed = config.get("random_seed")
    seed_declared = isinstance(seed, int) and not isinstance(seed, bool) and seed >= 0
    parameters = config.get("key_parameters")
    expected_parameters = {
        "question_candidate_minimum_characters",
        "question_candidate_debounce_ms",
        "potential_boundary_samples_per_regime_default",
        "potential_boundary_samples_per_regime_allowed_range",
        "ising_default_seed",
    }
    parameter_shape = isinstance(parameters, dict) and expected_parameters.issubset(parameters)
    allowed_range = parameters.get("potential_boundary_samples_per_regime_allowed_range") if isinstance(parameters, dict) else None
    key_parameters_declared = (
        parameter_shape
        and all(
            isinstance(parameters[key], int) and not isinstance(parameters[key], bool) and parameters[key] >= 0
            for key in expected_parameters - {"potential_boundary_samples_per_regime_allowed_range"}
        )
        and isinstance(allowed_range, list)
        and len(allowed_range) == 2
        and all(isinstance(value, int) and not isinstance(value, bool) for value in allowed_range)
        and allowed_range[0] >= 1
        and allowed_range[0] <= parameters["potential_boundary_samples_per_regime_default"] <= allowed_range[1]
    )
    resources = config.get("external_resources")
    resources_disclosed = (
        isinstance(resources, list)
        and bool(resources)
        and all(
            isinstance(item, dict)
            and isinstance(item.get("name"), str) and item["name"].strip()
            and isinstance(item.get("purpose"), str) and item["purpose"].strip()
            and isinstance(item.get("version_or_access_date"), str) and item["version_or_access_date"].strip()
            and isinstance(item.get("required"), bool)
            for item in resources
        )
    )
    runtime_versions_declared = all(
        isinstance(config.get(key), str) and config[key].strip() for key in ("python", "node")
    )
    return {
        "seed_declared": seed_declared,
        "key_parameters_declared": bool(key_parameters_declared),
        "resources_disclosed": resources_disclosed,
        "runtime_versions_declared": runtime_versions_declared,
    }


def _has_files(path: Path, suffixes: str | tuple[str, ...]) -> bool:
    if not path.is_dir():
        return False
    allowed = (suffixes,) if isinstance(suffixes, str) else suffixes
    return any(candidate.is_file() and candidate.suffix in allowed for candidate in path.rglob("*"))
