import assert from 'node:assert/strict'
import test from 'node:test'
import { CosMatterReviewClient } from '../lib/client.js'
import { apply, inject, name } from '../lib/index.js'
const template = { run_id: 'run_1', trust_status: 'blank_human_candidate_screening_template_not_a_result', candidate_count: 1, candidates: [{ document_id: 'doc-1', title: 'Candidate', source: 'Sciverse', publication_year: 2025 }], decisions: [{ document_id: 'doc-1', decision: 'unreviewed', reason_codes: [] }] }
const recorded = { run_id: 'run_1', candidate_count: 1, decision_counts: { include_for_fulltext: 1 }, trust_status: 'human_reviewed_candidate_screening_not_scientific_evidence' }
const decisions = [{ document_id: 'doc-1', decision: 'include_for_fulltext', reason_codes: ['material_match', 'property_match'] }]
test('client keeps screening metadata bounded and requires full decisions', async () => { assert.throws(() => new CosMatterReviewClient({ baseUrl: 'https://example.com' })); const responses = [template, recorded]; const client = new CosMatterReviewClient({}, async () => new Response(JSON.stringify(responses.shift()), { status: 200 })); assert.equal((await client.template('run_1')).candidate_count, 1); assert.equal((await client.record('run_1', decisions)).candidate_count, 1); await assert.rejects(() => client.record('run_1', [{ ...decisions[0], reason_codes: [] }]), /invalid/) })
test('DSH apply registers only human screening tools', async () => { const tools = []; const events = []; let dispose; const responses = [template, recorded]; const originalFetch = globalThis.fetch; globalThis.fetch = async () => new Response(JSON.stringify(responses.shift()), { status: 200 }); apply({ tools: { register: tool => tools.push(tool) }, emit: (event, payload) => events.push([event, payload]), effect: effect => { dispose = effect() } }); assert.equal(name, 'cosmatter-review'); assert.deepEqual(inject, ['tools']); assert.deepEqual(tools.map(tool => tool.name), ['cosmatter_candidate_screening_template', 'cosmatter_candidate_screening_record']); await tools[0].execute({ run_id: 'run_1' }, { signal: new AbortController().signal }); const result = await tools[1].execute({ run_id: 'run_1', decisions }, { signal: new AbortController().signal }); assert.equal(result.candidate_count, 1); assert.deepEqual(events.map(item => item[0]), ['cosmatter-review/template-read', 'cosmatter-review/recorded']); dispose(); globalThis.fetch = originalFetch })
