import { For, createSignal } from "solid-js";
import type { ImportedBundle } from "./model";
import { zh } from "./zh";

const bi = (_zh: string, en: string) => zh(en);
type Proposal = { id: string; status: string; title: string; rationale: string; requirement: string; tone: "blue" | "teal" | "violet"; };
const PROPOSALS: Proposal[] = [
  { id: "counterexample", status: bi("开放问题", "OPEN QUESTION"), title: bi("设计反例检索", "Design a counterexample search"), rationale: bi("探索当前材料—性质关系在哪些明确边界条件下可能失效。", "Explore where the current material-property relationship may fail under a clear boundary condition."), requirement: bi("需要：批准的检索计划和条件模式", "Needs: approved query plan and condition schema"), tone: "blue" },
  { id: "normalization", status: bi("方法缺口", "METHOD GAP"), title: bi("归一化条件字段", "Normalise condition fields"), rationale: bi("在合并不同样品几何或测量路线的证据前，建立可比较字段。", "Build comparable fields before combining evidence from different sample geometries or measurement routes."), requirement: bi("需要：字段字典和审查者签字", "Needs: field dictionary and reviewer sign-off"), tone: "teal" },
  { id: "evidence", status: bi("证据缺口", "EVIDENCE GAP"), title: bi("扩展来源覆盖", "Expand source coverage"), rationale: bi("仅收集能够定位和复核的来源记录，并暴露剩余覆盖缺口。", "Collect only source records that can be located and reviewed, then expose remaining coverage gaps."), requirement: bi("需要：授权来源集和溯源检查", "Needs: authorised source set and provenance checks"), tone: "violet" },
];
export function ResearchExpansion(props: { bundle: ImportedBundle }) {
  const [armed, setArmed] = createSignal<string | null>(null);
  return <main class="discovery-stage expansion-stage"><header class="stage-header"><div><p class="stage-kicker">COSMATTER / 研究拓展 RESEARCH EXTENSION</p><h1>{bi("研究拓展", "Research extension")}</h1><p>{bi("将未解决的材料问题转化为明确、经人工批准的后续任务。", "Turn unresolved material questions into explicit, human-approved follow-up missions.")}</p></div><div class="stage-tools"><button type="button" aria-label={bi("上一个展望", "Previous horizon")}>{"\u4e0a\u4e00\u9879"}</button><button type="button" aria-label={bi("展望设置", "Horizon settings")}>{"\u8bbe\u7f6e"}</button><button type="button" aria-label={bi("下一个展望", "Next horizon")}>{"\u4e0b\u4e00\u9879"}</button></div></header><section class="expansion-brief"><span>{bi("当前任务", "Current mission")} <strong>{props.bundle.mission.missionId}</strong></span><span>{bi("已批准证据", "Approved evidence")} <strong>{props.bundle.evidenceCards.length}</strong></span><span>{bi("条件缺口", "Condition gaps")} <strong>{props.bundle.conditionMatrix.flatMap((row) => row.unknowns).length}</strong></span><span>{bi("报告状态", "Report status")} <strong>{props.bundle.report ? bi("可用", "available") : bi("未发布", "not released")}</strong></span></section><section class="horizon-intro"><p class="stage-kicker">研究地平线 / RESEARCH HORIZON</p><h2>{bi("不要过早关闭矛盾。", "Do not close a contradiction too early.")}</h2><p>{bi("这些是建议方向，不是生成的科学主张。只有研究者批准新任务边界与证据要求后，才可执行。", "These are proposed directions, not generated scientific claims. They become executable only after a researcher approves a new task boundary and evidence requirements.")}</p></section><section class="proposal-grid" aria-label={bi("后续研究建议", "Follow-up research proposals")}><For each={PROPOSALS}>{(proposal, index) => <article class={`proposal-card tone-${proposal.tone}`}><span>{String(index() + 1).padStart(2, "0")}</span><small>{proposal.status}</small><h2>{proposal.title}</h2><p>{proposal.rationale}</p><footer><em>{proposal.requirement}</em><button type="button" classList={{ armed: armed() === proposal.id }} onClick={() => setArmed(armed() === proposal.id ? null : proposal.id)}>{armed() === proposal.id ? bi("已标记复核", "Marked for review") : bi("标记复核", "Mark for review")}</button></footer></article>}</For></section><section class="approval-strip"><div><p class="stage-kicker">批准门禁 / APPROVAL GATE</p><strong>{armed() ? bi("一个建议方向已标记，等待人工复核。", "One proposed direction is marked for human review.") : bi("没有新的研究行动被激活。", "No new research action is armed.")}</strong></div><button type="button">{bi("创建已批准后续任务", "Create approved follow-up mission")}</button></section><footer class="stage-note">{bi("本页将未来工作与当前证据分开。预览不会启动新任务、外部检索或模型调用。", "This page keeps future work separate from current evidence. The preview starts no new mission, external query, or model call.")}</footer></main>;
}